development:
    dialect: mysql
    datasource: root@tcp(localhost:3306)/ca_development?charset=utf8&parseTime=true
    dir: migrations/mysql
    table: migrations

test:
    dialect: mysql
    datasource: root@tcp(localhost:3306)/ca_development?charset=utf8&parseTime=true
    dir: migrations/mysql
    table: migrations
